sudo: required

services:
    - docker

before_install:
    - docker-compose up -d
    - sleep 10

script:
    - curl -sSf http://localhost > /dev/null

after_failure:
    - timeout 3s docker-compose logs app db web
